mysql:
  username: ${DATABASE_MYSQL_USERNAME:brito}
  password: ${DATABASE_MYSQL_PASSWORD:9431DsdS%$}
  schema: adm_videos
  url: ${DATABASE_MYSQL_URL:localhost:3306}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none